eureka:
  client:
    instance:
      preferIpAddress: 'true'
    register-with-eureka: 'true'
    fetch-register: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
